[package]
name = "WordSentences"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "network/*"
]
[dependencies]
libc = "0.2.168"
tokio = { version = "1.42.0", features = ["full"] }

[dependencies.http]
path = "network/http"